trigger:
  branches:
    include:
      - "*"

pr:
  branches:
    include:
      - "*"

jobs:
  - job: Terraform Plan
    displayName: Run Tests
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        submodules: true
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        inputs:
          terraformVersion: "1.4.6"
      - task: CmdLine@2
        inputs:
          script: |
            terraform init && terraform plan
